/**
 * Hero ID to Hero Name mapping for Dota 2
 * Based on OpenDota hero data
 */
export const HERO_NAMES = {
  1: 'Anti-Mage',
  2: 'Axe',
  3: 'Bane',
  4: 'Bloodseeker',
  5: 'Crystal Maiden',
  6: 'Drow Ranger',
  7: 'Earthshaker',
  8: 'Juggernaut',
  9: 'Mirana',
  10: 'Morphling',
  11: 'Shadow Fiend',
  12: 'Puck',
  13: 'Pudge',
  14: 'Razor',
  15: 'Sand King',
  16: 'Storm Spirit',
  17: 'Sven',
  18: 'Tiny',
  19: 'Vengeful Spirit',
  20: 'Windranger',
  21: 'Zeus',
  22: 'Kunkka',
  23: 'Lina',
  25: 'Lion',
  26: 'Shadow Shaman',
  27: 'Slardar',
  28: 'Tidehunter',
  29: 'Witch Doctor',
  30: 'Lich',
  31: 'Riki',
  32: 'Enigma',
  33: 'Tinker',
  34: 'Sniper',
  35: 'Necrophos',
  36: 'Warlock',
  37: 'Beastmaster',
  38: 'Queen of Pain',
  39: 'Venomancer',
  40: 'Faceless Void',
  41: 'Wraith King',
  42: 'Death Prophet',
  43: 'Phantom Assassin',
  44: 'Pugna',
  45: 'Templar Assassin',
  46: 'Viper',
  47: 'Luna',
  48: 'Dragon Knight',
  49: 'Dazzle',
  50: 'Clockwerk',
  51: 'Leshrac',
  52: "Nature's Prophet",
  53: 'Lifestealer',
  54: 'Dark Seer',
  55: 'Clinkz',
  56: 'Omniknight',
  57: 'Enchantress',
  58: 'Huskar',
  59: 'Night Stalker',
  60: 'Broodmother',
  61: 'Bounty Hunter',
  62: 'Weaver',
  63: 'Jakiro',
  64: 'Batrider',
  65: 'Chen',
  66: 'Spectre',
  67: 'Ancient Apparition',
  68: 'Doom',
  69: 'Ursa',
  70: 'Spirit Breaker',
  71: 'Gyrocopter',
  72: 'Alchemist',
  73: 'Invoker',
  74: 'Silencer',
  75: 'Outworld Destroyer',
  76: 'Lycan',
  77: 'Brewmaster',
  78: 'Shadow Demon',
  79: 'Lone Druid',
  80: 'Chaos Knight',
  81: 'Meepo',
  82: 'Treant Protector',
  83: 'Ogre Magi',
  84: 'Undying',
  85: 'Rubick',
  86: 'Disruptor',
  87: 'Nyx Assassin',
  88: 'Naga Siren',
  89: 'Keeper of the Light',
  90: 'Io',
  91: 'Visage',
  92: 'Slark',
  93: 'Medusa',
  94: 'Troll Warlord',
  95: 'Centaur Warrunner',
  96: 'Magnus',
  97: 'Timbersaw',
  98: 'Bristleback',
  99: 'Tusk',
  100: 'Skywrath Mage',
  101: 'Abaddon',
  102: 'Elder Titan',
  103: 'Legion Commander',
  104: 'Techies',
  105: 'Ember Spirit',
  106: 'Earth Spirit',
  107: 'Underlord',
  108: 'Terrorblade',
  109: 'Phoenix',
  110: 'Oracle',
  111: 'Winter Wyvern',
  112: 'Arc Warden',
  113: 'Monkey King',
  114: 'Dark Willow',
  119: 'Grimstroke',
  120: 'Mars',
  121: 'Snapfire',
  123: 'Void Spirit',
  126: 'Hoodwink',
  128: 'Dawnbreaker',
  129: 'Marci',
  135: 'Primal Beast',
  136: 'Muerta',
  137: 'Muerta'
};

/**
 * Get hero name by ID
 */
export function getHeroName(heroId) {
  return HERO_NAMES[heroId] || `Hero ${heroId}`;
}

/**
 * Get hero image URL from OpenDota CDN
 */
export function getHeroImageUrl(heroId) {
  return `https://cdn.dota2.com/apps/dota2/images/heroes/${getHeroName(heroId).toLowerCase().replace(/\s+/g, '_').replace(/'/g, '')}_full.png`;
}

